### ISSUE TITLE
WordPress Version is Out of Date

### ISSUE THREAD

**Issue by rcallenmg** [pantheon-systems/wordpress-composer#16] opened 2021-06-21 19:52 UTC
Current WordPress version (5.7.2) was released 12 May 2021. This repository is only updated to 5.4.1

**Comment by greg-1-anderson** [comment] 2021-06-29 16:31
It seems that the issue is that the new releases are not being merged onto the master branch; however, the tags exist in this repository, and they are also available in Packagist.

**Comment by greg-1-anderson** [comment] 2021-06-29 20:34
I merged all of the tagged commits onto the master branch; however, this is not being done automatically yet. To ensure that your project stays up-to-date, ensure that you are requesting a stable version of pantheon-systems/wordpress-composer, not dev-master. There are two good ways to do that:

1. Use `"pantheon-systems/wordpress-composer": "^5"` in your composer.json. You will occasionally need to change this to ^6 or ^7.
2. If you want to keep using `"pantheon-systems/wordpress-composer": "*"`, use minimum stability "stable" rather than "dev"

**Closed as completed by greg-1-anderson** 2021-06-29 20:34 UTC
